### ISSUE TITLE
如何使用默认ipv4

### ISSUE THREAD

**Issue by rfnb** [EddieIvan01/iox#1]
启用代理时默认为ipv6，怎么改ipv4

**Comment by EddieIvan01** [comment]
如果host同时具备ipv4和ipv6地址，Go默认会监听ipv6（`:::1080`），但这个不会影响客户端使用ipv4地址访问

**Comment by rfnb** [comment]
我用iox -proxy -l 1111 -k 000d22 代理端是 centos 8 查看lsof -i:1111 也只有 ipv6 反正测试几次就不行就没测试了。
别一个在国内的设备测试 
iox -r xxxx:1111 -k 000d22
一直不行，

**Comment by EddieIvan01** [comment]
我在CentOS 7上一切正常

你需要确认端口是否通畅，检查iptables规则或firewall，或尝试`sysctl net.ipv6.conf.all.disable_ipv6`

如果你使用的是v0.2版本，可以尝试在release页重新下载v0.2再次尝试
