### ISSUE TITLE
0.5版本

### ISSUE THREAD

**Issue by DongHuangT1** [EddieIvan01/iox#15]
大佬，请问0.5版本什么时候发布啊，我看已经有0.5的分支了。

**Comment by EddieIvan01** [comment]
0.5-beta分支的iox已经可以使用了，修改了命令行参数，增加了IO多路复用，增加了KCP传输协议支持等

**Comment by DongHuangT1** [comment]
> 大佬，请问0.5版本什么时候发布啊，我看已经有0.5的分支了。
