### ISSUE TITLE
HcK?

### ISSUE THREAD

**Issue by fasdfx** [EddieIvan01/iox#16]
HI, GUYS YOUR TOOL IS  SO COOL BUT.. THERE ARE SOME UNFIRENDLY CONNECTIONS.....

**Comment by EddieIvan01** [comment]
unfirendly or unfriendly?
Describe the issue clearly plz

**Comment by fasdfx** [comment]
some connections to other computer,you know.

**Comment by EddieIvan01** [comment]
interesting
