### ISSUE TITLE
sock4 和 http代理

### ISSUE THREAD

**Issue by Nan3r** [EddieIvan01/iox#2]
很好用的工具，希望能支持sock4 和 http代理

**Comment by EddieIvan01** [comment]
暂时没有该打算，考虑到：

+ 大多数情况下一种代理协议已足够使用

+ 作为一个Gadget性质的工具（而不是类似FRP那样Service性质的工具），需要保持功能精简，避免增大二进制文件体积

**Comment by Nan3r** [comment]
好的，谢谢
