### ISSUE TITLE
server与client多路复用功能

### ISSUE THREAD

**Issue by FunnyWolf** [EddieIvan01/iox#3]
使用chrome等浏览器挂上socks5代理后,通常访问一个网页会建立多个tcp链接,从netio代码看会导致server与client间建立多个tcp连接,能否加入多路复用功能,使用一个tcp连接进行控制,一个tcp连接传输数据?

**Comment by EddieIvan01** [comment]
因为现有的五种模式都是可以不成对使用的（要兼容直接与其他socket连接），所以要实现你的需求需要添加新的转发模式，而且新添加的模式必须成对使用才能完成逻辑信道的编解码

例如
```
./iox fwd -mux -l 1080 -r 127.0.0.1:9999
./iox proxy -mux -l 9999
```

这样的做法实际上是把不同的功能集成在同一个工具上，会导致臃肿和增加不必要的复杂度，我希望该工具能保持精简便携

未来可能会考虑添加该功能，但不会放在master分支

**Comment by EddieIvan01** [comment]
0db18f3 
v0.4在反向代理中添加TCP多路复用
