### ISSUE TITLE
portforward command 

### ISSUE THREAD

**Issue by Chantal2019** [EddieIvan01/iox#5]
Can someone please help me the equivalent of this command with IOX 

rportfwd [bind port] [forward host] [forward port] --- > this is the way I can do it in Cobalt strike

How can I do it with IOX?
for example if I am doing this in Cobalt rportfwd 8004 10.8.0.x 443 how would I do it with IOX?

**Comment by EddieIvan01** [comment]
Assume that your teamserver IP is 1.1.1.1

On your beacon victim:
```
./iox -r 10.8.0.1:443 -r 1.1.1.1:9999
```

On your teamserver:
```
./iox -l 8004 -l 9999
```

Then your teamserver `1.1.1.1:8004` is forwarded to `10.8.0.1:443` which is in intranet

**Comment by Chantal2019** [comment]
Thank you soooo much for replying even though this is not an issue. Appreciate it! This is a great tool and I really want to start using it. So let me just explain something quickly! My team server ip is 10.8.0.80 for example and the beacon I am running on victim is for example 10.10.21.113 ( internal victim ip). So what I want to do is forward everthing to my local 443 port on my team server .

So I cobalt with the default port forward is easy since I will do rportfed 8004 10.8.0 80 ( my team server ip ) 443 : this will open a listining port on vitim on port 8004.

you are telling me to do ./iox -r 10.8.0.1:443 -r 1.1.1.1:9999 which I do not understand . is 10.8.0.1:443 the vitim address for example ?

**Comment by EddieIvan01** [comment]
Ooo sorry, I have misunderstood the `rportfwd` function

***

Easily run this command on victim machine

```
./iox -l 8004 -r 10.8.0.80:443
```

**Comment by Chantal2019** [comment]
thank you :)

**Comment by Chantal2019** [comment]
keep getting 
```Unrecognized Mode```

Maybe I need to do ./iox fwd -l 8004 -r 10.8.0.80:443 Instead ?

**Comment by EddieIvan01** [comment]
Sorry, my mistake, use `./iox fwd -l 8004 -r 10.8.0.80:443`
