### ISSUE TITLE
 i/o timeout

### ISSUE THREAD

**Issue by DarknightCanada** [EddieIvan01/iox#7]
any idea why the tool si giving me this error

 beacon> shell iox.exe fwd -l 9004 -r 10.8.0.86:443
[*] Tasked beacon to run: iox.exe fwd -l 9004 -r 10.8.0.86:443
[+] host called home, sent: 67 bytes
[+] received output:
[*] Forward between :9004 and 10.8.0.86:443

[+] received output:
[!] Connect remote 10.8.0.86:443 error: dial tcp 10.8.0.86:443: i/o timeout
[!] Connect remote 10.8.0.86:443 error: dial tcp 10.8.0.86:443: i/o timeout

[+] received output:
[!] Connect remote 10.8.0.86:443 error: dial tcp 10.8.0.86:443: i/o timeout

[+] received output:
[!] Connect remote 10.8.0.86:443 error: dial tcp 10.8.0.86:443: i/o timeout

[+] received output:
[!] Connect remote 10.8.0.86:443 error: dial tcp 10.8.0.86:443: i/o timeout
[!] Connect remote 10.8.0.86:443 error: dial tcp 10.8.0.86:443: i/o timeout

[+] received output:
[!] Connect remote 10.8.0.86:443 error: dial tcp 10.8.0.86:443: i/o timeout
[!] Connect remote 10.8.0.86:443 error: dial tcp 10.8.0.86:443: i/o timeout

**Comment by EddieIvan01** [comment]
Try to increase timeout duration via `-t`

```
iox.exe fwd -l 9004 -r 10.8.0.86:443 -t 10000
```

**Comment by DarknightCanada** [comment]
Hey Man!

The reason I am very interested in this tools is that I want to introduce
it in RTO (rasta course) Is there any way I can share the video that how
the error happens? I am using it in cobaltstrike

**Comment by EddieIvan01** [comment]
What does RTO(rasta course) mean? 

You need to make sure the beacon-machine could connect to 10.8.0.86:443, if it could, then increase timeout duration
