### ISSUE TITLE
"Using iox as a simple ShadowSocks-like"具有加密处理吗？

### ISSUE THREAD

**Issue by briteming** [EddieIvan01/iox#8]
hi.
在服务器上，我运行了：
iox proxy -l 19999 -k 000102

在本机上，我运行了：
iox fwd -l 1081 -r VPS-public-ip:19999 -k 000102
然后设置本地机器上的浏览器的socks5代理为127.0.0.1:1081，浏览器确实可以翻墙，但从2边的参数看，总感觉没有做加密处理似的。
谢谢回复

**Comment by EddieIvan01** [comment]
参数加`*`代表启用加密

```
 iox proxy -l *19999 -k 000102
 iox fwd -l 1081 -r *IP:19999 -k 000102
```
